# Generated by Django 5.1 on 2024-08-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
